In [1]:
import numpy as np

from rate_model import RateModelWC
from resp_predictor_2 import ResponsePredictor_2

In [2]:
# Model
N = 5  # Number of populations
W = 0.2 * np.random.randn(N, N)  # Weight matrix
model = RateModelWC(W, tau=1, rmax=10, gain_slope=0.5, gain_center=0)
model.sim_res_type = 'final'

# External input
h0 = 1 * np.random.randn(N, 1)

pred = ResponsePredictor_2(model)
pred.set_h0(h0)
pred.train(dh=0.1, dr=0.1)

L = np.zeros((N, N))
V = np.zeros((N, N))
for n in range(N):
    J2 = pred.J2[n, :, :]
    L[:, n], V_ = np.linalg.eig(J2)
    V[:, n] = V_[:, 0]

L /= L[0, :]

np.set_printoptions(formatter={'float': lambda x: f'{x:.02e}'})
#print(np.log(np.abs(L)))
print(L)
#print(V)

[[1.00e+00 1.00e+00 1.00e+00 1.00e+00 1.00e+00]
 [5.61e-10 5.17e-10 2.92e-11 -4.26e-10 1.67e-09]
 [3.21e-13 -4.90e-12 1.18e-12 4.81e-13 -1.82e-13]
 [-4.39e-14 -2.62e-12 -2.07e-13 -8.74e-14 1.93e-12]
 [7.24e-14 2.40e-12 -1.10e-12 -5.76e-15 2.78e-12]]


In [3]:
J20 = pred.J2
pred._calc_J2_estim(dr=0.1)
J2 = pred.J2

In [16]:
#print(J20[0, :, :])
#print()
#print(J2[0, :, :])
n = 3
np.max(np.abs(J20[n, :] - J2[n, :]).ravel()) / np.max(np.abs(J20[n, :]))

4.155944903003237e-05